### PR TITLE
More robust pauserc parsing

### PR DESCRIPTION
**Pull request by shlomif**
Hi @rjbs!

This pull-req:

1. Extracts a method to facilitate testing.

2. Errs on a line without a "key value" pair (with a test).

3. Corrects a typo (with a test).

Please consider merging it and let me know if there's anything else you need.

### CODE REVIEW

**Comment by shlomif** [comment]
Ping! Why wasn't this merged yet?

**Comment by shlomif** [comment]
Ping.

**Comment by micwoj92** [comment]
This branch has conflicts that must be resolved

**Comment by shlomif** [comment]
@micwoj92 : i resolved the conflicts now, and `dzil test --all` passes locally. Nevertheless, I am annoyed by this mismanagement. @rjbs !

**Comment by micwoj92** [comment]
Thanks, I hope it can be merged/reviewed now...

**Comment by rjbs** [comment]
Thanks, I've rebased this, fiddled with the layout a bit, added the line number of bad lines, and applied!

**Comment by shlomif** [comment]
> Thanks, I've rebased this, fiddled with the layout a bit, added the line number of bad lines, and applied!

Thanks!

**Pull request closed without merging**
